///|
typealias @env.Env

///|
typealias @parser.PrimExpr

///|
typealias @parser.ConstantExpr

///|
typealias @parser.(PostFixExpr, PostFixSuffix)

///|
typealias @parser.(UnaryExpr, UnaryPrefix, UnaryExprBody, UnaryOperator)

///|
typealias @parser.CastExpr

///|
typealias @parser.(MultExpr, MultOp)

///|
typealias @parser.(AddSubExpr, AddSubOp)

///|
typealias @parser.(ShiftExpr, ShiftOp)

///|
typealias @parser.(RelationalExpr, RelationalOp)

///|
typealias @parser.(EqualityExpr, EqualityOp)

///|
typealias @parser.(AndExpr, ExclusiveOrExpr, InclusiveOrExpr)

///|
typealias @parser.(LogicalAndExpr, LogicalOrExpr)

///|
typealias @parser.ConditionalExpr

///|
typealias @parser.AssignExpr

///|
typealias @parser.Expr

///|
typealias @parser.Declaration

///|
typealias @parser.DeclSpec

///|
typealias @parser.StorageClassSpec

///|
typealias @parser.TypeSpec

///|
typealias @parser.TypeQualifier

///|
typealias @parser.TypeSpecOrQualifier

///|
typealias @parser.(StructSpec, UnionSpec)

///|
typealias @parser.(StructDeclaration, StructDeclarator)

///|
typealias @parser.Declarator

///|
typealias @parser.Pointer

///|
typealias @parser.DirectDeclarator

///|
typealias @parser.InitDeclarator

///|
typealias @parser.Initializer

///|
typealias @parser.Designator

///|
typealias @parser.EnumSpec

///|
typealias @parser.Enumerator

///|
typealias @parser.FunctionSpec

///|
typealias @parser.AlignmentSpec

///|
typealias @parser.TypeName

///|
typealias @parser.AbstractDeclarator

///|
typealias @parser.DirectAbstractDeclarator

///|
typealias @parser.Statement

///|
typealias @parser.LabeledStatement

///|
typealias @parser.CompoundStatement

///|
typealias @parser.BlockItem

///|
typealias @parser.SelectionStatement

///|
typealias @parser.IterationStatement

///|
typealias @parser.(ForCondition, ForInit)

///|
typealias @parser.JumpStatement

///|
typealias @parser.CompilationUnit

///|
typealias @parser.ExternalDeclaration

///|
typealias @parser.FunctionDefinition

///|
typealias @parser.ParameterTypeList

///|
typealias @parser.ParameterDecl

///|
typealias @parser.ParamDeclarator

///|
typealias @parser.ParserContext
